name = "nordisk-mobilvask"
main = "src/worker.js"
compatibility_date = "2026-07-20"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = [ "/", "/api/*", "/portal*" ]

[observability]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "nordisk-mobilvask-test-db"
database_id = "0ba2ef68-d701-4e7b-afe0-9cc32d7bdf5d"
migrations_dir = "migrations"
